/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Status = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
});
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'asistenmu' : IDL.Null });
export const User = IDL.Record({
  'status' : Status,
  'nama' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : Role,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'idUser' : IDL.Text,
  'principalId' : IDL.Text,
});

export const idlService = IDL.Service({
  'claimAdmin' : IDL.Func([], [], []),
  'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getMyRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isAdminClaimed' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Status = IDL.Variant({ 'active' : IDL.Null, 'pending' : IDL.Null });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'asistenmu' : IDL.Null });
  const User = IDL.Record({
    'status' : Status,
    'nama' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : Role,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'idUser' : IDL.Text,
    'principalId' : IDL.Text,
  });
  
  return IDL.Service({
    'claimAdmin' : IDL.Func([], [], []),
    'getMyProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getMyRole' : IDL.Func([], [IDL.Opt(Role)], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isAdminClaimed' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };