/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminLog {
  'action' : string,
  'adminPrincipalId' : string,
  'createdAt' : bigint,
  'idLog' : string,
  'targetId' : string,
}
export interface Client {
  'status' : Status,
  'nama' : string,
  'createdAt' : bigint,
  'role' : Role,
  'whatsapp' : string,
  'email' : string,
  'company' : string,
  'idUser' : string,
  'principalId' : string,
}
export type FPRequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface FinancialProfile {
  'createdAt' : bigint,
  'nomorRekening' : string,
  'namaRekening' : string,
  'namaBankEwallet' : string,
}
export interface FinancialProfileRequest {
  'status' : FPRequestStatus,
  'partnerNama' : string,
  'newProfile' : FinancialProfile,
  'createdAt' : bigint,
  'partnerId' : string,
  'oldProfile' : [] | [FinancialProfile],
  'idRequest' : string,
}
export type LevelPartner = { 'junior' : null } |
  { 'senior' : null } |
  { 'expert' : null };
export interface Partner {
  'status' : Status,
  'kota' : string,
  'nama' : string,
  'createdAt' : bigint,
  'role' : Role,
  'verifiedSkill' : Array<string>,
  'whatsapp' : string,
  'email' : string,
  'level' : LevelPartner,
  'idUser' : string,
  'principalId' : string,
}
export type Role = { 'client' : null } |
  { 'admin' : null } |
  { 'operasional' : null } |
  { 'public' : null } |
  { 'asistenmu' : null } |
  { 'partner' : null };
export interface Service {
  'unitLayanan' : bigint,
  'status' : ServiceStatus,
  'clientPrincipalId' : string,
  'tipeLayanan' : TipeLayanan,
  'clientNama' : string,
  'createdAt' : bigint,
  'asistenmuNama' : string,
  'hargaPerLayanan' : bigint,
  'sharingLayanan' : Array<SharingEntry>,
  'asistenmuPrincipalId' : string,
  'idService' : string,
}
export type ServiceStatus = { 'active' : null } |
  { 'inactive' : null };
export interface SharingEntry {
  'nama' : string,
  'idUser' : string,
  'principalId' : string,
}
export type Status = { 'reject' : null } |
  { 'active' : null } |
  { 'pending' : null } |
  { 'suspend' : null };
export interface Task {
  'unitLayanan' : bigint,
  'status' : TaskStatus,
  'clientId' : string,
  'partnerNama' : string,
  'clientNama' : string,
  'notesAsistenmu' : string,
  'asistenmuId' : string,
  'createdAt' : bigint,
  'jamEfektif' : bigint,
  'asistenmuNama' : string,
  'deadline' : bigint,
  'detailTask' : string,
  'partnerId' : string,
  'linkGdriveInternal' : string,
  'linkGdriveClient' : string,
  'serviceId' : string,
  'idTask' : string,
  'judulTask' : string,
}
export type TaskStatus = { 'revisi' : null } |
  { 'reviewclient' : null } |
  { 'ditolak' : null } |
  { 'permintaanbaru' : null } |
  { 'qaasistenmu' : null } |
  { 'selesai' : null } |
  { 'onprogress' : null };
export type TipeLayanan = { 'fokus' : null } |
  { 'jaga' : null } |
  { 'rapi' : null } |
  { 'tenang' : null } |
  { 'efisien' : null };
export interface TopUp {
  'createdAt' : bigint,
  'unitTambahan' : bigint,
  'idService' : string,
  'idTopUp' : string,
  'namaClient' : string,
}
export interface User {
  'status' : Status,
  'nama' : string,
  'createdAt' : bigint,
  'role' : Role,
  'whatsapp' : string,
  'email' : string,
  'idUser' : string,
  'principalId' : string,
}
export interface WalletInfo {
  'saldoTersedia' : bigint,
  'saldoPengajuan' : bigint,
}
export interface WithdrawRequest {
  'status' : WithdrawStatus,
  'partnerNama' : string,
  'nominal' : bigint,
  'idWithdraw' : string,
  'createdAt' : bigint,
  'partnerId' : string,
  'nomorRekening' : string,
  'namaRekening' : string,
  'namaBankEwallet' : string,
}
export type WithdrawStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _SERVICE {
  'aktivasiLayanan' : ActorMethod<
    [
      TipeLayanan,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      Array<SharingEntry>,
    ],
    string
  >,
  'approveClient' : ActorMethod<[Principal], undefined>,
  'approveFinancialProfileRequest' : ActorMethod<[string], undefined>,
  'approveInternalUser' : ActorMethod<[Principal, Role], undefined>,
  'approvePartner' : ActorMethod<[Principal], undefined>,
  'approveWithdraw' : ActorMethod<[string], undefined>,
  /**
   * / Archive a service (admin/operasional only)
   */
  'archiveService' : ActorMethod<[string], undefined>,
  'claimAdmin' : ActorMethod<[string, string, string], undefined>,
  'createTask' : ActorMethod<
    [string, string, bigint, string, string, string, string, string],
    string
  >,
  'delegasiTask' : ActorMethod<
    [string, string, string, bigint, bigint, string, string, string],
    undefined
  >,
  /**
   * / Admin Functions
   */
  'forceClaimAdmin' : ActorMethod<[string, string, string], undefined>,
  'getAdminLogs' : ActorMethod<[], Array<AdminLog>>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllPartners' : ActorMethod<[], Array<Partner>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllTasksByAsistenmu' : ActorMethod<[], Array<Task>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  /**
   * / Get all archived services (admin/operasional only)
   */
  'getArchivedServices' : ActorMethod<[], Array<Service>>,
  'getAsistenmu' : ActorMethod<[], Array<User>>,
  'getClients' : ActorMethod<[], Array<Client>>,
  'getFPRequestStatus' : ActorMethod<[string], [] | [FPRequestStatus]>,
  'getFinancialProfileByPartnerId' : ActorMethod<
    [string],
    [] | [FinancialProfile]
  >,
  'getFinancialProfileRequests' : ActorMethod<
    [],
    Array<FinancialProfileRequest>
  >,
  /**
   * / NEW FUNCTION: Get client profile of the caller
   */
  'getMyClientProfile' : ActorMethod<[], [] | [Client]>,
  'getMyFinancialProfile' : ActorMethod<[], [] | [FinancialProfile]>,
  'getMyPartnerProfile' : ActorMethod<[], [] | [Partner]>,
  'getMyProfile' : ActorMethod<[], [] | [User]>,
  /**
   * / Get role of the caller
   */
  'getMyRole' : ActorMethod<[], [] | [Role]>,
  'getMyServicesAsAsistenmu' : ActorMethod<[], Array<Service>>,
  'getMyServicesAsClient' : ActorMethod<[], Array<Service>>,
  /**
   * / NEW FUNCTION: Get tasks for the currently logged in client
   */
  'getMyTasksAsClient' : ActorMethod<[], Array<Task>>,
  /**
   * / NEW FUNCTION: Get tasks for the currently logged in partner
   */
  'getMyTasksAsPartner' : ActorMethod<[], Array<Task>>,
  'getMyWallet' : ActorMethod<[], WalletInfo>,
  'getMyWithdrawRequests' : ActorMethod<[], Array<WithdrawRequest>>,
  'getPartners' : ActorMethod<[], Array<Partner>>,
  'getServiceStatus' : ActorMethod<[string], [] | [ServiceStatus]>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getTaskStatus' : ActorMethod<[string], [] | [TaskStatus]>,
  'getTasksByAsistenmu' : ActorMethod<[], Array<Task>>,
  'getTasksByPartner' : ActorMethod<[], Array<Task>>,
  'getTopUps' : ActorMethod<[], Array<TopUp>>,
  /**
   * / Get status of user by principal
   */
  'getUserStatus' : ActorMethod<[Principal], [] | [Status]>,
  /**
   * / Get all users, partners, clients, services, topups, etc.
   */
  'getUsers' : ActorMethod<[], Array<User>>,
  'getWithdrawRequests' : ActorMethod<[], Array<WithdrawRequest>>,
  'getWithdrawStatus' : ActorMethod<[string], [] | [WithdrawStatus]>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'isAdminClaimed' : ActorMethod<[], boolean>,
  'reactivateClient' : ActorMethod<[Principal], undefined>,
  'reactivatePartner' : ActorMethod<[Principal], undefined>,
  'reactivateUser' : ActorMethod<[Principal], undefined>,
  'registerClient' : ActorMethod<[string, string, string, string], string>,
  'registerPartner' : ActorMethod<[string, string, string, string], string>,
  'registerUser' : ActorMethod<[string, string, string], string>,
  'rejectClient' : ActorMethod<[Principal], undefined>,
  'rejectFinancialProfileRequest' : ActorMethod<[string], undefined>,
  'rejectPartner' : ActorMethod<[Principal], undefined>,
  'rejectUser' : ActorMethod<[Principal], undefined>,
  'rejectWithdraw' : ActorMethod<[string], undefined>,
  'requestFinancialProfile' : ActorMethod<[string, string, string], string>,
  'requestWithdraw' : ActorMethod<[bigint], string>,
  'suspendClient' : ActorMethod<[Principal], undefined>,
  'suspendPartner' : ActorMethod<[Principal], undefined>,
  'suspendUser' : ActorMethod<[Principal], undefined>,
  'topUpService' : ActorMethod<[string, bigint], string>,
  'updateMyPartnerProfile' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updatePartnerDetails' : ActorMethod<
    [Principal, LevelPartner, Array<string>],
    undefined
  >,
  'updateService' : ActorMethod<
    [string, ServiceStatus, Array<SharingEntry>],
    undefined
  >,
  'updateTaskStatus' : ActorMethod<[string, TaskStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];